version = 5.4.0
archive_dir = /etc/letsencrypt/archive/videepthamdfoods.com
cert = /etc/letsencrypt/live/videepthamdfoods.com/cert.pem
privkey = /etc/letsencrypt/live/videepthamdfoods.com/privkey.pem
chain = /etc/letsencrypt/live/videepthamdfoods.com/chain.pem
fullchain = /etc/letsencrypt/live/videepthamdfoods.com/fullchain.pem
[renewalparams]
account = e4d6404b3b381c399d3b65e3736d1875
pref_challs = http-01,
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
